jserv:
  server:
    port: 8080
    host: localhost
  cors:
    enabled: true
    origin: "http://foo.localhost:8080"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    headers:
      - "*"